---
name: "robot-framework-"

on:
  push:
    branches:
      - test_develop

jobs:
  create-env:
    runs-on: "self-hosted"
    steps:
      - name: "Checkout source code"
        uses: "actions/checkout@v2.3.4"
        with:
          fetch-depth: 0
      
      - name: "Create or restore the python virtualenv"
        uses: syphar/restore-virtualenv@v1
        id: cache-virtualenv
        with:
          requirement_files: tests/requirements.txt

      - uses: syphar/restore-pip-download-cache@v1
        if: steps.cache-virtualenv.outputs.cache-hit != 'true'

        # the package installation will only be executed when the
        # requirements-files have changed.
      - run: pip install -r tests/requirements.txt
        if: steps.cache-virtualenv.outputs.cache-hit != 'true'
    
  robot-framework-csc-tests:
    needs: create-env
    runs-on: "self-hosted"
    steps:
      - name: "Use the previoulsy created virtualenv"
        uses: syphar/restore-virtualenv@v1
        id: cache-virtualenv
      
      - name: "Runs the robot-framework tests"
        run: robot -o output/output -l output/log -r output/report tests/*.robot